window.onload = init;
function init(){
    generateQuote()
}

function generateQuote(){
    /*console.log("new quote")*/
    let randomIndex = Math.floor(Math.random() * QUOTEBANK.length);
    let randomQuote = QUOTEBANK[randomIndex];
    
    let twitterLink = "https://twitter.com/intent/tweet?text="
    
    let quoteInApiFormat = randomQuote.quote.replace(/ /g, "%20");
    twitterLink += quoteInApiFormat;
    let authorInApiFormat = randomQuote.author.replace(/ /g, "%20");

    twitterLink += " - " + authorInApiFormat ;
    

    document.getElementById("text").innerText = randomQuote.quote;
    document.getElementById("author").innerText = randomQuote.author;
    document.getElementById("tweet-quote").href = twitterLink;
}

const QUOTEBANK = [
        {author:"José Saramago",
        quote:"Gostar é provavelmente a melhor maneira de ter, ter deve ser a pior maneira de gostar."}, 
       {author:"José Saramago",
        quote:"Não tenhamos pressa, mas não percamos tempo."}, 
       {author:"José Saramago",
        quote:"Dentro de nós há uma coisa que não tem nome, essa coisa é o que somos."}, 
       {author:"José Saramago",
        quote:"Se tens um coração de ferro, bom proveito. O meu, fizeram-no de carne, e sangra todo dia."}, 
       {author:"José Saramago",
        quote:"Todos sabemos que cada dia que nasce é o primeiro para uns e será o último para outros e que, para a maioria, é só um dia mais."}, 
       {author:"José Saramago",
        quote:"De que adianta falar de motivos, às vezes basta um só, às vezes nem juntando todos."}, 
       {author:"José Saramago",
        quote:"Dirão, em som, as coisas que, calados, no silêncio dos olhos confessamos?"}, 
       {author:"José Saramago",
        quote:"O que as vitórias têm de mau é que não são definitivas. O que as derrotas têm de bom é que também não são definitivas."}, 
       {author:"José Saramago",
        quote:"Se podes olhar, vê. Se podes ver, repara."}, 
       {author:"José Saramago",
        quote:"Há esperanças que é loucura ter. Pois eu digo-te que se não fossem essas já eu teria desistido da vida."}, 
       {author:"José Saramago",
        quote:"Para temperamentos nostálgicos, em geral quebradiços, pouco flexíveis, viver sozinho é um duríssimo castigo."}, 
       {author:"José Saramago",
        quote:"Fisicamente, habitamos um espaço, mas, sentimentalmente, somos habitados por uma memória."}, 
       {author:"José Saramago",
        quote:"O espelho e os sonhos são coisas semelhantes, é como a imagem do homem diante de si próprio."}, 
       {author:"José Saramago",
        quote:"O que dá o verdadeiro sentido ao encontro é a busca, e é preciso andar muito para se alcançar o que está perto."}, 
       {author:"José Saramago",
        quote:"Sempre chega a hora em que descobrimos que sabíamos muito mais do que antes julgávamos."}, 
       {author:"José Saramago",
        quote:"Mesmo que a rota da minha vida me conduza a uma estrela, nem por isso fui dispensado de percorrer os caminhos do mundo."}, 
       {author:"José Saramago",
        quote:"Nada é para sempre, dizemos, mas há momentos que parecem ficar suspensos, pairando sobre o fluir inexorável do tempo."}, 
       {author:"José Saramago",
        quote:"Cada dia traz sua alegria e sua pena, e também sua lição proveitosa."}, 
       {author:"José Saramago",
        quote:"As palavras proferidas pelo coração não tem língua que as articule, retém-nas um nó na garganta e só nos olhos é que se podem ler."}, 
       {author:"José Saramago",
        quote:"O difícil não é viver com as pessoas, o difícil é compreendê-las."}, 
       {author:"José Saramago",
        quote:"A única maneira de liquidar o dragão é cortar-lhe a cabeça, aparar-lhe as unhas não serve de nada."}, 
       {author:"José Saramago",
        quote:"Não sou pessimista. O mundo é que é péssimo."}, 
       {author:"José Saramago",
        quote:"Tentei não fazer nada na vida que envergonhasse a criança que fui."}, 
       {author:"José Saramago",
        quote:"Se eu estiver a ser sincero hoje, que importa que tenha de arrepender-me amanhã?"}, 
       {author:"José Saramago",
        quote:"Se não disseres nada compreenderei melhor [...], há ocasiões em que as palavras não servem de nada."}, 
       {author:"José Saramago",
        quote:"Aprendi a não tentar convencer ninguém. O trabalho de convencer é uma falta de respeito, é uma tentativa de colonização do outro."}, 
       {author:"José Saramago",
        quote:"A vida é breve, mas cabe nela muito mais do que somos capazes de viver."}, 
       {author:"José Saramago",
        quote:"Arranca metade do meu corpo, do meu coração, dos meus sonhos. Tira um pedaço de mim, qualquer coisa que me desfaça. Me recria, porque eu não suporto mais pertencer a tudo, mas não caber em lugar algum."}, 
       {author:"José Saramago",
        quote:"O problema não é um Deus que não existe, mas a religião que O proclama!"}, 
       {author:"José Saramago",
        quote:"Nunca se pode saber de antemão de que são capazes as pessoas, é preciso esperar, dar tempo ao tempo, o tempo é que manda, o tempo é o parceiro que está a jogar do outro lado da mesa e tem na mão todas as cartas do baralho, a nós compete-nos inventar os encartes com a vida..."}, 
       {author:"José Saramago",
        quote:"Ainda está por nascer o primeiro ser humano desprovido daquela segunda pele a que chamamos de egoísmo, bem mais dura que a outra, que por qualquer coisa sangra."}, 
       {author:"José Saramago",
        quote:"Costuma-se dizer que as paredes têm ouvidos, imagine-se o tamanho que terão as orelhas das estrelas."}, 
       {author:"José Saramago",
        quote:"O certo e o errado são apenas modos diferentes de entender nossa relação com os outros."}, 
       {author:"José Saramago",
        quote:"O silêncio ainda é o melhor aplauso."}, 
       {author:"José Saramago",
        quote:"O costume de cair endurece o corpo, ter chegado ao chão, só por si, já é um alívio."}, 
       {author:"José Saramago",
        quote:"Não nos vemos se não nos saímos de nós."}, 
       {author:"José Saramago",
        quote:"Damos voltas e voltas, mas, na realidade, só há duas coisas: ou escolhes a vida ou afastas-te dela."}, 
       {author:"José Saramago",
        quote:"Não é a pornografia que é obscena, é a fome que é obscena."}, 
       {author:"José Saramago",
        quote:"Os únicos interessados em mudar o mundo são os pessimistas, porque os otimistas estão encantados com o que há..."}, 
       {author:"José Saramago",
        quote:"Não se percebeu ainda que o instinto serve melhor aos animais do que a razão serve ao homem."}, 
       {author:"José Saramago",
        quote:"Em rigor, não tomamos decisões, são as decisões que nos tomam a nós."}, 
       {author:"José Saramago",
        quote:"O Bem e o Mal não existem em si mesmos, cada um é somente a ausência do outro."}, 
       {author:"José Saramago",
        quote:"Toda a obra literária leva uma pessoa dentro, que é o autor. O autor é um pequeno mundo entre outros pequenos mundos"}, 
       {author:"José Saramago",
        quote:"Nós somos manipulados, enganados, desde que nascemos!"}, 
       {author:"José Saramago",
        quote:"Nunca terá sido perdido o dia em que fomos contemplados, ao menos, com um bom conselho."}, 
       {author:"José Saramago",
        quote:"Não se pode trabalhar num esgoto sem cheirar a esgoto."}, 
       {author:"José Saramago",
        quote:"A esperança é como o sal, não alimenta, mas dá sabor ao pão."}, 
       {author:"José Saramago",
        quote:"Quando a esquerda chega ao poder, não usa as razões pelas quais chegou. A esquerda deixa de o ser muitas vezes quando chega ao poder e isso é dramático."}, 
       {author:"José Saramago",
        quote:"A palavra deixou de ter conteúdo e de ter qualquer coisa dentro, é pronunciada com uma leviandade total."}, 
       {author:"José Saramago",
        quote:"Costuma-se dizer, dêmos tempo ao tempo, mas aquilo que sempre nos esquecemos de perguntar é se haverá tempo para dar."}, 
       {author:"José Saramago",
        quote:"É desta massa que nós somos feitos: metade de indiferença, outra metade de maldade."}, 
       {author:"José Saramago",
        quote:"Nunca esperei nada da vida. Por isso tenho tudo."}, 
       {author:"José Saramago",
        quote:"Quando a igreja inventou o pecado, inventou um instrumento de controle, não tanto das almas, porque à igreja não importam as almas, mas dos corpos."}, 
       {author:"José Saramago",
        quote:"Aprendi que o sentimento do amor não é mais nem menos forte conforme as idades, o amor é uma possibilidade de uma vida inteira, e se acontece, há que recebê-lo."}, 
       {author:"José Saramago",
        quote:"O bem e o mal não existem em si mesmos, cada um deles é somente a ausência do outro.”"}, 
       {author:"José Saramago",
        quote:"Olhar, ver e reparar são maneiras distintas de usar o órgão da vista. Só o reparar, no entanto, pode chegar a ser visão plena."}, 
       {author:"José Saramago",
        quote:"...É preciso voltar aos passos que foram dados, para repetir e para traçar caminhos novos ao lado deles. É preciso recomeçar a viagem. Sempre."}, 
       {author:"José Saramago",
        quote:"Os sismógrafos não escolhem os terremotos, reagem aos que vão ocorrendo, e o blog é isso, um sismógrafo."}, 
       {author:"José Saramago",
        quote:"Por causa e em nome de Deus é que se tem permitido e justificado tudo, principalmente o mais horrendo e cruel."}, 
       {author:"José Saramago",
        quote:"Não posso crer num deus que foi capaz de criar o ser humano."}, 
       {author:"José Saramago",
        quote:"A cabeça dos seres humanos nem sempre está completamente de acordo com o mundo em que vivem, há pessoas que tem dificuldade em ajustar-se à realidade dos factos, no fundo não passam de espíritos débeis e confusos que usam as palavras, às vezes habilmente, para justificar a sua covardia."}, 
       {author:"José Saramago",
        quote:"Há coisas que nunca se poderão explicar por palavras."}, 
       {author:"José Saramago",
        quote:"A lucidez é um luxo que nem todos se podem permitir."}, 
       {author:"José Saramago",
        quote:"Nem a juventude sabe o que pode, nem a velhice pode o que sabe."}, 
       {author:"José Saramago",
        quote:"Os politicos são a mentira, legitimada pela vontade do povo!"}, 
       {author:"José Saramago",
        quote:"O sofrimento em silêncio causa uma doença silenciosa: A Insanidade Mental!"}, 
       {author:"José Saramago",
        quote:"Ser-se homem não deveria significar nunca impedimento a proceder como cavalheiro."}, 
       {author:"José Saramago",
        quote:"A vida é uma aprendizagem diária. Afasto-me do caos e sigo um simples pensamento: Quanto mais simples, melhor!"}, 
       {author:"José Saramago",
        quote:"É preciso variar, se não tivermos cuidado a vida torna-se rapidamente previsível, monótona, uma seca."}, 
       {author:"José Saramago",
        quote:"É preciso sair da ilha para ver a ilha. Não nos vemos se não saímos de nós."}, 
       {author:"José Saramago",
        quote:"Não sou um ateu total, todos os dias tento encontrar um sinal de Deus, mas infelizmente não o encontro."}, 
       {author:"José Saramago",
        quote:"Das habilidades que o mundo sabe, essa ainda é a que faz melhor: dar voltas."}, 
       {author:"José Saramago",
        quote:"Existem duas superpotências no Mundo, uma é os E.U.A, outra, és tu..."}, 
       {author:"José Saramago",
        quote:"Saberemos cada vez menos o que é um ser humano"}, 
       {author:"José Saramago",
        quote:"A alegoria chega quando descrever a realidade já não nos serve"}, 
       {author:"José Saramago",
        quote:"Quero encontrar a ilha desconhecida, quero saber quem sou quando nela estiver."}, 
       {author:"José Saramago",
        quote:"Num matrimônio há três pessoas: o Homem, a Mulher e a terceira pessoa formada pelos dois."}, 
       {author:"José Saramago",
        quote:"É ainda possível chorar sobre as páginas de um livro, mas não se pode derramar lágrimas sobre um disco rígido."}, 
       {author:"José Saramago",
        quote:"Estamos usando nosso cérebro de maneira excessivamente disciplinada, pensando só o que é preciso pensar, o que se nos permite pensar."}, 
       {author:"José Saramago",
        quote:"As pessoas se transformam em máquinas de fazer de dinheiro ou que tentam fazer dinheiro."}, 
       {author:"José Saramago",
        quote:"A propósito, não resistiremos a recordar que a morte, por si mesma, sozinha, sem qualquer ajuda externa, sempre matou muito menos que o homem."}, 
       {author:"José Saramago",
        quote:"Somos todos escritores, só que alguns escrevem e outros não."}, 
       {author:"José Saramago",
        quote:"É assim a vida, vai dando com uma mão até que chega o dia em que tira tudo com a outra."}, 
       {author:"José Saramago",
        quote:"A leitura é, provavelmente, uma outra maneira de estar em um lugar."}, 
       {author:"José Saramago",
        quote:"Quero estar onde minha sombra estiver, se lá é que estiverem os teus olhos."},
        {author:"Fernando Pessoa",
        quote:"Amo como ama o amor. Não conheço nenhuma outra razão para amar senão amar. Que queres que te diga, além de que te amo, se o que quero dizer-te é que te amo?"},
        {author:"Fernando Pessoa",
        quote:"Às vezes ouço passar o vento; e só de ouvir o vento passar, vale a pena ter nascido."},
        {author:"Fernando Pessoa",
        quote:"Tudo vale a pena quando a alma não é pequena."},
        {author:"Fernando Pessoa",
        quote:"Tenho em mim todos os sonhos do mundo."},
        {author:"Fernando Pessoa",
        quote:"Tenho pensamentos que, se pudesse revelá-los e fazê-los viver, acrescentariam nova luminosidade às estrelas, nova beleza ao mundo e maior amor ao coração dos homens."},
        {author:"Fernando Pessoa",
        quote:"A liberdade é a possibilidade do isolamento. Se te é impossível viver só, nasceste escravo."},
        {author:"Fernando Pessoa",
        quote:"Para viajar basta existir."},
        {author:"Fernando Pessoa",
        quote:"O próprio viver é morrer, porque não temos um dia a mais na nossa vida que não tenhamos, nisso, um dia a menos nela."},
        {author:"Fernando Pessoa",
        quote:"Adoramos a perfeição, porque não a podemos ter; repugna-la-íamos se a tivéssemos. O perfeito é o desumano porque o humano é imperfeito."},
        {author:"Fernando Pessoa",
        quote:"O meu passado é tudo quanto não consegui ser. Nem as sensações de momentos idos me são saudosas: o que se sente exige o momento; passado este, há um virar de página e a história continua, mas não o texto."},
        {author:"Fernando Pessoa",
        quote:"Querer não é poder. Quem pôde, quis antes de poder só depois de poder. Quem quer nunca há-de poder, porque se perde em querer."},
        {author:"Fernando Pessoa",
        quote:"Matar o sonho é matarmo-nos. É mutilar a nossa alma. O sonho é o que temos de realmente nosso, de impenetravelmente e inexpugnavelmente nosso."},
        {author:"Fernando Pessoa",
        quote:"Sentir é criar. Sentir é pensar sem ideias, e por isso sentir é compreender, visto que o Universo não tem ideias."},
        {author:"Fernando Pessoa",
        quote:"Quero para mim o espírito desta frase, transformada a forma para a casar com o que eu sou: Viver não é necessário; o que é necessário é criar."},
        {author:"Fernando Pessoa",
        quote:"Precisar de dominar os outros é precisar dos outros. O chefe é um dependente."},
        {author:"Fernando Pessoa",
        quote:"Toda a poesia - e a canção é uma poesia ajudada - reflete o que a alma não tem. Por isso a canção dos povos tristes é alegre e a canção dos povos alegres é triste."},
        {author:"Fernando Pessoa",
        quote:"Amar é cansar-se de estar só: é uma covardia portanto, e uma traição a nós próprios (importa soberanamente que não amemos)."},
        {author:"Fernando Pessoa",
        quote:"A arte é a autoexpressão lutando para ser absoluta."},
        {author:"Fernando Pessoa",
        quote:"Eu não escrevo em português. Escrevo eu mesmo."},
        {author:"Fernando Pessoa",
        quote:"Considerar a nossa maior angústia como um incidente sem importância, não só na vida do universo mas da nossa mesma alma, é o princípio da sabedoria."},
        {author:"Fernando Pessoa",
        quote:"Haja ou não deuses, deles somos servos."},
        {author:"Fernando Pessoa",
        quote:"A renúncia é a libertação. Não querer é poder."},
        {author:"Fernando Pessoa",
        quote:"Nunca sabemos quando somos sinceros. Talvez nunca o sejamos. E mesmo que sejamos sinceros hoje, amanhã podemos sê-lo por coisa contrária."},
        {author:"Fernando Pessoa",
        quote:"Sinto-me nascido a cada momento; Para a eterna novidade do Mundo..."},
        {author:"Fernando Pessoa",
        quote:"O mundo é de quem não sente. A condição essencial para se ser um homem prático é a ausência de sensibilidade."},
        {author:"Fernando Pessoa",
        quote:"Para realizar um sonho é preciso esquecê-lo, distrair dele a atenção. Por isso realizar é não realizar."},
        {author:"Fernando Pessoa",
        quote:"De sonhar ninguém se cansa, porque sonhar é esquecer, e esquecer não pesa e é um sono sem sonhos em que estamos despertos."},
        {author:"Fernando Pessoa",
        quote:"O gênio, o crime e a loucura, provêm, por igual, de uma anormalidade; representam, de diferentes maneiras, uma inadaptabilidade ao meio."},
        {author:"Fernando Pessoa",
        quote:"Tudo que existe existe talvez porque outra coisa existe. Nada é, tudo coexiste: talvez assim seja certo."},
        {author:"Fernando Pessoa",
        quote:"Ter opiniões é estar vendido a si mesmo. Não ter opiniões é existir. Ter todas as opiniões é ser poeta."},
        {author:"Fernando Pessoa",
        quote:"O amor é um sono que chega para o pouco ser que se é"},
        {author:"Fernando Pessoa",
        quote:"Ver e ouvir são as únicas coisas nobres que a vida contém. Os outros sentidos são plebeus e carnais. A única aristocracia é nunca tocar."},
        {author:"Fernando Pessoa",
        quote:"Tudo que se passa no onde vivemos é em nós que se passa. Tudo que cessa no que vemos é em nós que cessa."},
        {author:"Fernando Pessoa",
        quote:"A ciência descreve as coisas como são; a arte, como são sentidas, como se sente que são."},
        {author:"Fernando Pessoa",
        quote:"É preciso ser um realista para descobrir a realidade. É preciso ser um romântico para criá-la."},
        {author:"Fernando Pessoa",
        quote:"A bondade é a delicadeza das almas grosseiras."},
        {author:"Fernando Pessoa",
        quote:"O fim da arte inferior é agradar, o fim da arte média é elevar, o fim da arte superior é libertar."},
        {author:"Fernando Pessoa",
        quote:"Todo o homem de ação é essencialmente animado e otimista porque quem não sente é feliz."},
        {author:"Fernando Pessoa",
        quote:"Quanto mais diferente de mim alguém é, mais real me parece, porque menos depende da minha subjetividade."},
        {author:"Fernando Pessoa",
        quote:"As figuras imaginárias têm mais relevo e verdade que as reais."},
        {author:"Fernando Pessoa",
        quote:"Conhece alguém as fronteiras à sua alma, para que possa dizer - eu sou eu?"},
        {author:"Fernando Pessoa",
        quote:"A única maneira de teres sensações novas é construíres-te uma alma nova."},
        {author:"Fernando Pessoa",
        quote:"O dinheiro é belo, porque é a libertação."},
        {author:"Fernando Pessoa",
        quote:"Há tanta suavidade em nada dizer e tudo entender..."},
        {author:"Fernando Pessoa",
        quote:"Nenhum livro para crianças deve ser escrito para crianças."},
        {author:"Fernando Pessoa",
        quote:"Saber interpor-se constantemente entre si próprio e as coisas é o mais alto grau de sabedoria e prudência."},
        {author:"Fernando Pessoa",
        quote:"Podemos morrer se apenas amámos."},
        {author:"Fernando Pessoa",
        quote:"A fé é o instinto da ação..."},
        {author:"Fernando Pessoa",
        quote:"Deus é o existirmos e isto não ser tudo."},
        {author:"Fernando Pessoa",
        quote:"A vida prejudica a expressão da vida. Se eu vivesse um grande amor nunca o poderia contar."},
        {author:"Fernando Pessoa",
        quote:"O mais alto de nós não é mais que um conhecedor mais próximo do oco e do incerto de tudo."},
        {author:"Fernando Pessoa",
        quote:"Pode ser que nos guie uma ilusão; a consciência, porém, é que nos não guia."},
        {author:"Fernando Pessoa",
        quote:"Falar é ter demasiada consideração pelos outros. Pela boca morrem o peixe e Oscar Wilde."},
        {author:"Fernando Pessoa",
        quote:"As nações são todas mistérios. Cada uma é todo o mundo a sós."},
        {author:"Fernando Pessoa",
        quote:"A felicidade está fora da felicidade."},
        {author:"Fernando Pessoa",
        quote:"Exteriorizar impressões é mais persuadirmo-nos de que as temos do que termo-las."},
        {author:"Fernando Pessoa",
        quote:"A celebridade é uma contradição. Parecendo que dá valor e força às criaturas, apenas as desvaloriza e enfraquece."},
    
        
];
